services:
  - type: web
    name: jbdon
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.html
        name: Cache-Control
        value: public, max-age=3600
